name: shrishti_creatives
description: A Flutter app for Shrishti Creatives

# The version of the app
version: 1.0.0+1

# Flutter SDK version constraint
environment:
  sdk: "^3.7.0"  # Ensure compatibility with Dart 3.7 and above

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.0  # Make sure you use the latest version of the webview plugin

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"
